### ISSUE TITLE
Correct Glottolog mappings

### ISSUE THREAD

**Issue by xrotwang** [lexibank/grollemundbantu#8]
Via @d97hah

> I've had reason to look over the Grollemund 2015 language id:s again and I noticed some errors, mostly because I realized many of the lists were in Grollemund 2012 were the sources are given, which is far more information than just the name. My best understanding is reflected in the lgcode-part of the latest hh.bib.

**Comment by SimonGreenhill** [comment]
Fixed in https://github.com/lexibank/grollemundbantu/commit/5428bbf68843d2649ac33b704407375add6a92bd
